# Server
server.port=8082
spring.application.name=feed-service

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/feeddb
spring.data.mongodb.database=feeddb

# Multipart upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

# UserAndInterest service base URL
user.service.base-url=http://localhost:8081

# Logging
logging.level.com.hobbyconnect.feedservice=DEBUG